# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def fibonacci_sum(limit)
  x = 1
  y = 0
  z = 0
  sum = 0

  while z < limit
    z = x + y
    if z.even?
      sum += z
    end
    y = x
    x = z
  end
  return sum
end
